image: ubuntu

artifacts:
- path: MySampleNuGetLib
  name: my_app
- path: MySampleNuGetLib.sln
  name: my_file

deploy:
- provider: FTP
  host: waws-prod-bay-003.ftp.azurewebsites.windows.net
  protocol: ftp
  username: ftp-test\$ftp-test
  password:
    secure: QK/04+2Xw6GiUwVtVTBGoWMzL2OITqOo6jtE+LbtFYYY7vSSz/eWB2I0IgvodT9tIsfh/2K15feUhIiOL2cNFg==
  folder: /site/wwwroot
  artifact: my_file
  application: my_app
  debug: true

build: off
test: off
